- name: Catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disable old nodejs 
    ansible.builtin.shell: dnf module disable nodejs -y ;

  - name: enable nodejs-18
    ansible.builtin.shell:  dnf module enable nodejs:18 -y
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present



